export const SCHOOL_DATA_LIST = 'SCHOOL_DATA_LIST'
export const SCHOOL_TREE_LIST = 'SCHOOL_TREE_LIST'
export const GROUP_TREE_LIST = 'GROUP_TREE_LIST'
export const CHANGE_LOAD_STATUS = 'CHANGE_LOAD_STATUS'
